server:
  port: 9090
spring:
  application:
    name: internal-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          httpserver:
            wiretap: true
          httpclient:
            wiretap: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

enable:
  kafka: ${ENABLE_KAFKA:false}

security:
  enabled: ${SECURITY_ENABLED:false}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 30000

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 60
    lease-expiration-duration-in-seconds: 180
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter: trace
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace