server:
  port: 9090
spring:
  application:
    name: server-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


zuul:
  routes:
    products:
      path: /inventory/**
      serviceId: inventory-service
  prefix: /api
